@startuml
'https://plantuml.com/class-diagram

class Company{
    designation
}

class VaccinationCenter{
    name
    address
    phoneNumber
    email
    fax
    website
    openingAndClosingHours
    slotDuration
    maxVaccinesPerSlot
    numberOfVaccinated
}

class System

class VaccineAdministration{
    timeOfAdministration
    slot
    waitingRoom
    recoveryRoom
}
Company "1" --- "*" VaccinationCenter: > manages
Company "1" - "1" System: > manages
VaccineAdministration "1" - "1" VaccinationCenter: > performed at
@enduml