@startuml
'https://plantuml.com/use-case-diagram

left to right direction

rectangle System {
  usecase "Registers the arrival of a SNSUser to take the vaccine" as UC4
}

:Receptionist: as Rcp

Rcp -- UC4
@enduml