@startuml
'https://plantuml.com/use-case-diagram

left to right direction

rectangle System {
  usecase "Registration Process" as UC1
  usecase "Schedule Vaccine" as UC2
  usecase "Request Certificate" as UC3

  usecase "Emit Certificate" as UC4

  usecase "Register Centers and Employees" as UC5

  usecase "Configure and Manage Application Information " as UC6

  usecase "Monitor Vaccination Process" as UC7

  usecase "Notify User" as UC8
  usecase "Indicate Vacccine" as UC9

  usecase "Confirm Schedule" as UC10

  usecase "Authorizes SMS notification" as UC11

  usecase "Provides user data" as UC12


}

:SNS User: as User
:Nurse: as Nurse
:Receptionists: as Recep
:coordinator: as coord
:Administrator: as Admin
:AdministratorDGS: as AdminDGS
:system: as system

User -- UC1
User -- UC2
User -- UC3

Nurse -- UC1
Nurse -- UC2
Nurse -- UC4

AdminDGS -- UC5

Admin -- UC6

coord -- UC7

system -- UC8
system -- UC9

Recep -- UC10

UC1 -- UC11
UC1 -- UC12







@enduml